name: 'Artifact-DL'
description: "Artifact-DL allows you to download all of the artifacts of a Workflow or many workflows. Just specify the commits of the workflows you would like to download artifacts for as a JSON list for the input."

inputs:
  repo_path:
    description: 'Location of the Git Repository'
    required: false
    default: '/github/workspace/'
  git_token:
    description: 'Token used for authenticating with the upstream repository'
    required: true
  input_commits:
    description: 'JSON list of commits to download artifacts for.'
    required: true
  output_path:
    description: 'Path to write the outputted files to.'
    required: false
    default: '/github/workspace/'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/autamus/artifact-dl:latest'
branding:
  icon: 'download'
  color: 'white'
